import type { Therapist } from './types';

// ─────────────────────────────────────────────────────────────────────────
// Mock provider directory (~12 therapists). Public, non-PHI data.
//
// SEAM: in production this comes from a verified-provider service. Replace
// `therapists` with a typed fetch; keep the `Therapist` shape stable so the
// match algorithm and UI don't change. Verification (`verified`,
// `licenseNumber`) would be backed by license-board + malpractice checks.
// ─────────────────────────────────────────────────────────────────────────

const directory: Therapist[] = [
  {
    id: 'maya-okafor',
    name: 'Dr. Maya Okafor',
    pronouns: 'she/her',
    gender: 'female',
    credentials: [{ abbrev: 'PsyD', label: 'Doctor of Psychology' }],
    licenseNumber: 'PSY-29184',
    licenseState: 'NY',
    verified: true,
    yearsExperience: 12,
    headline: 'Anxiety and burnout for high-pressure careers.',
    bio: "I work with people who look fine on paper and feel frayed underneath — founders, clinicians, attorneys, new parents. We'll find the patterns driving the overwhelm and build tools that hold up on your worst days, not just your calm ones. My style is direct, warm, and practical: you should leave most sessions with something to try.",
    city: 'Brooklyn',
    state: 'NY',
    concerns: ['anxiety', 'stress-burnout', 'depression'],
    modalities: ['CBT', 'ACT', 'Mindfulness'],
    delivery: ['remote', 'in-person'],
    values: ['secular', 'lgbtq-affirming'],
    insurance: ['Aetna', 'Cigna', 'Out-of-network'],
    sessionRate: 220,
    slidingScale: false,
    acceptingClients: true,
    nextAvailable: 'This week',
    availability: [
      { day: 'Mon', times: ['9:00 AM', '5:30 PM'] },
      { day: 'Wed', times: ['12:00 PM', '6:00 PM'] },
      { day: 'Thu', times: ['8:00 AM'] },
    ],
    languages: ['English'],
    rating: 4.9,
    reviewCount: 86,
  },
  {
    id: 'daniel-reyes',
    name: 'Daniel Reyes',
    pronouns: 'he/him',
    gender: 'male',
    credentials: [{ abbrev: 'LMFT', label: 'Licensed Marriage & Family Therapist' }],
    licenseNumber: 'LMFT-104522',
    licenseState: 'CA',
    verified: true,
    yearsExperience: 9,
    headline: 'Couples work and repair after rupture.',
    bio: "Most couples don't arrive because they've stopped loving each other — they arrive because they've stopped feeling heard. I use Emotionally Focused and Gottman-informed work to slow down the fights, surface what's underneath, and rebuild trust at a pace you can both feel. I also see individuals navigating relationship transitions and divorce.",
    city: 'Los Angeles',
    state: 'CA',
    concerns: ['relationships', 'family', 'stress-burnout'],
    modalities: ['Couples', 'Psychodynamic', 'Person-Centered'],
    delivery: ['in-person', 'remote'],
    values: ['secular', 'culturally-responsive', 'lgbtq-affirming'],
    insurance: ['Kaiser', 'Anthem', 'Out-of-network'],
    sessionRate: 180,
    slidingScale: true,
    acceptingClients: true,
    nextAvailable: 'Next week',
    availability: [
      { day: 'Tue', times: ['10:00 AM', '7:00 PM'] },
      { day: 'Sat', times: ['9:00 AM', '11:00 AM'] },
    ],
    languages: ['English', 'Spanish'],
    rating: 4.8,
    reviewCount: 54,
  },
  {
    id: 'sarah-bensen',
    name: 'Sarah Bensen',
    pronouns: 'she/her',
    gender: 'female',
    credentials: [{ abbrev: 'LCSW', label: 'Licensed Clinical Social Worker' }],
    licenseNumber: 'LCSW-77310',
    licenseState: 'TX',
    verified: true,
    yearsExperience: 15,
    headline: 'Trauma and EMDR, at your pace.',
    bio: "Trauma isn't only the event — it's the way the body keeps bracing long after. I'm an EMDR-certified therapist and I never rush the work. We build safety and resourcing first, then process when you're ready. I see survivors of abuse, accidents, medical trauma, and first responders. You set the pace; I hold the structure.",
    city: 'Austin',
    state: 'TX',
    concerns: ['trauma', 'anxiety', 'grief'],
    modalities: ['EMDR', 'IFS', 'Mindfulness'],
    delivery: ['remote'],
    values: ['secular', 'veteran-informed', 'culturally-responsive'],
    insurance: ['Blue Cross Blue Shield', 'United', 'Out-of-network'],
    sessionRate: 160,
    slidingScale: true,
    acceptingClients: true,
    nextAvailable: 'This week',
    availability: [
      { day: 'Mon', times: ['11:00 AM', '2:00 PM'] },
      { day: 'Wed', times: ['9:00 AM'] },
      { day: 'Fri', times: ['1:00 PM', '3:00 PM'] },
    ],
    languages: ['English'],
    rating: 5.0,
    reviewCount: 71,
  },
  {
    id: 'james-whitfield',
    name: 'Pastor James Whitfield',
    pronouns: 'he/him',
    gender: 'male',
    credentials: [
      { abbrev: 'LPC', label: 'Licensed Professional Counselor' },
      { abbrev: 'MDiv', label: 'Master of Divinity' },
    ],
    licenseNumber: 'LPC-55021',
    licenseState: 'GA',
    verified: true,
    yearsExperience: 18,
    headline: 'Faith-integrated counseling for anxiety and grief.',
    bio: "For people who want their faith in the room, not left at the door. I'm a licensed counselor and an ordained minister, and I integrate Christian practice with evidence-based care — never one at the expense of the other. We can pray together or not; the clinical work stays rigorous either way. I often see folks through loss, doubt, and burnout in ministry.",
    city: 'Atlanta',
    state: 'GA',
    concerns: ['grief', 'anxiety', 'depression', 'identity'],
    modalities: ['Faith-Based', 'Person-Centered', 'CBT'],
    delivery: ['in-person', 'remote'],
    values: ['christian', 'culturally-responsive'],
    insurance: ['Out-of-network', 'Self-pay'],
    sessionRate: 140,
    slidingScale: true,
    acceptingClients: true,
    nextAvailable: 'This week',
    availability: [
      { day: 'Tue', times: ['9:00 AM', '4:00 PM'] },
      { day: 'Thu', times: ['10:00 AM', '5:00 PM'] },
    ],
    languages: ['English'],
    rating: 4.9,
    reviewCount: 63,
  },
  {
    id: 'priya-nair',
    name: 'Dr. Priya Nair',
    pronouns: 'she/her',
    gender: 'female',
    credentials: [{ abbrev: 'PhD', label: 'Doctor of Clinical Psychology' }],
    licenseNumber: 'PSY-41902',
    licenseState: 'IL',
    verified: true,
    yearsExperience: 11,
    headline: 'Identity, culture, and the immigrant experience.',
    bio: "Between two cultures, you can feel like you're never fully home in either. I work with first- and second-generation clients on identity, family expectation, and the quiet grief of leaving places behind. The work is collaborative and curious — we honor where you come from while making room for who you're becoming.",
    city: 'Chicago',
    state: 'IL',
    concerns: ['identity', 'anxiety', 'family', 'depression'],
    modalities: ['Psychodynamic', 'ACT', 'Person-Centered'],
    delivery: ['remote', 'in-person'],
    values: ['culturally-responsive', 'secular', 'lgbtq-affirming'],
    insurance: ['Aetna', 'United', 'Out-of-network'],
    sessionRate: 190,
    slidingScale: false,
    acceptingClients: true,
    nextAvailable: 'Next week',
    availability: [
      { day: 'Mon', times: ['1:00 PM'] },
      { day: 'Wed', times: ['10:00 AM', '6:30 PM'] },
      { day: 'Fri', times: ['9:00 AM'] },
    ],
    languages: ['English', 'Hindi', 'Malayalam'],
    rating: 4.8,
    reviewCount: 49,
  },
  {
    id: 'rebecca-stein',
    name: 'Rebecca Stein',
    pronouns: 'she/her',
    gender: 'female',
    credentials: [{ abbrev: 'LCSW', label: 'Licensed Clinical Social Worker' }],
    licenseNumber: 'LCSW-30887',
    licenseState: 'NY',
    verified: true,
    yearsExperience: 7,
    headline: 'Eating concerns and body image, without shame.',
    bio: "Recovery isn't about willpower and it isn't linear. I work with disordered eating, chronic dieting, and body image using a Health-at-Every-Size, anti-diet lens. We'll build a relationship with food and your body that doesn't run your day. I coordinate with dietitians and physicians when that's part of your care.",
    city: 'New York',
    state: 'NY',
    concerns: ['eating', 'anxiety', 'identity'],
    modalities: ['DBT', 'CBT', 'IFS'],
    delivery: ['remote', 'in-person'],
    values: ['jewish', 'lgbtq-affirming', 'secular'],
    insurance: ['Cigna', 'Oxford', 'Out-of-network'],
    sessionRate: 175,
    slidingScale: true,
    acceptingClients: true,
    nextAvailable: 'This week',
    availability: [
      { day: 'Tue', times: ['8:30 AM', '3:00 PM'] },
      { day: 'Thu', times: ['12:00 PM', '5:30 PM'] },
    ],
    languages: ['English'],
    rating: 4.9,
    reviewCount: 38,
  },
  {
    id: 'marcus-bell',
    name: 'Marcus Bell',
    pronouns: 'he/him',
    gender: 'male',
    credentials: [{ abbrev: 'LPC', label: 'Licensed Professional Counselor' }],
    licenseNumber: 'LPC-66120',
    licenseState: 'CA',
    verified: true,
    yearsExperience: 6,
    headline: 'Men, anger, and what sits underneath it.',
    bio: "A lot of men were taught one acceptable emotion. I help unpack the anger, numbness, and pressure into something workable — without lectures or shame. We talk straight. I see a lot of guys navigating fatherhood, career identity, and relationships, plus veterans readjusting to civilian life.",
    city: 'San Diego',
    state: 'CA',
    concerns: ['stress-burnout', 'relationships', 'identity', 'depression'],
    modalities: ['CBT', 'ACT', 'Person-Centered'],
    delivery: ['in-person', 'remote', 'mobile'],
    values: ['veteran-informed', 'secular', 'culturally-responsive'],
    insurance: ['TRICARE', 'Anthem', 'Out-of-network'],
    sessionRate: 150,
    slidingScale: true,
    acceptingClients: true,
    nextAvailable: 'This week',
    availability: [
      { day: 'Mon', times: ['7:00 AM', '6:00 PM'] },
      { day: 'Wed', times: ['7:00 AM'] },
      { day: 'Sat', times: ['10:00 AM'] },
    ],
    languages: ['English'],
    rating: 4.7,
    reviewCount: 42,
  },
  {
    id: 'aisha-rahman',
    name: 'Aisha Rahman',
    pronouns: 'she/her',
    gender: 'female',
    credentials: [{ abbrev: 'LMHC', label: 'Licensed Mental Health Counselor' }],
    licenseNumber: 'LMHC-22045',
    licenseState: 'FL',
    verified: true,
    yearsExperience: 8,
    headline: 'Faith-aligned care for Muslim women and families.',
    bio: "Therapy that understands your faith and your family without needing it explained. I support Muslim women and families through anxiety, marriage, parenting, and identity, integrating Islamic values where you want them present. The space is confidential, unhurried, and yours.",
    city: 'Orlando',
    state: 'FL',
    concerns: ['anxiety', 'family', 'relationships', 'identity'],
    modalities: ['Faith-Based', 'CBT', 'Mindfulness'],
    delivery: ['remote'],
    values: ['muslim', 'culturally-responsive'],
    insurance: ['Florida Blue', 'Out-of-network', 'Self-pay'],
    sessionRate: 130,
    slidingScale: true,
    acceptingClients: true,
    nextAvailable: 'This week',
    availability: [
      { day: 'Sun', times: ['1:00 PM', '4:00 PM'] },
      { day: 'Wed', times: ['11:00 AM', '8:00 PM'] },
    ],
    languages: ['English', 'Arabic', 'Urdu'],
    rating: 5.0,
    reviewCount: 57,
  },
  {
    id: 'tom-castellano',
    name: 'Tom Castellano',
    pronouns: 'he/him',
    gender: 'male',
    credentials: [{ abbrev: 'LCSW', label: 'Licensed Clinical Social Worker' }],
    licenseNumber: 'LCSW-90433',
    licenseState: 'MA',
    verified: true,
    yearsExperience: 21,
    headline: 'Addiction and recovery, with no judgment.',
    bio: "I've spent two decades in addiction and recovery work, and I've never met a person who wanted to be where their addiction took them. Whether you're sober-curious, in early recovery, or rebuilding after relapse, we meet you where you are. I draw on motivational interviewing and harm-reduction alongside family work.",
    city: 'Boston',
    state: 'MA',
    concerns: ['addiction', 'depression', 'family', 'trauma'],
    modalities: ['Person-Centered', 'CBT', 'DBT'],
    delivery: ['in-person', 'remote'],
    values: ['secular', 'lgbtq-affirming'],
    insurance: ['Blue Cross Blue Shield', 'Tufts', 'Out-of-network'],
    sessionRate: 165,
    slidingScale: true,
    acceptingClients: false,
    nextAvailable: 'Waitlist',
    availability: [{ day: 'Thu', times: ['2:00 PM'] }],
    languages: ['English', 'Italian'],
    rating: 4.9,
    reviewCount: 94,
  },
  {
    id: 'grace-lim',
    name: 'Dr. Grace Lim',
    pronouns: 'she/her',
    gender: 'female',
    credentials: [{ abbrev: 'PsyD', label: 'Doctor of Psychology' }],
    licenseNumber: 'PSY-38771',
    licenseState: 'WA',
    verified: true,
    yearsExperience: 10,
    headline: 'Depression and life transitions in your 20s–30s.',
    bio: "Quarter-life stuckness is real: the job, the move, the breakup, the sense that everyone else got a manual you didn't. I help younger adults move through depression and big transitions with a mix of structure and self-compassion. Expect a warm, slightly nerdy collaborator who takes your goals seriously.",
    city: 'Seattle',
    state: 'WA',
    concerns: ['depression', 'anxiety', 'identity', 'stress-burnout'],
    modalities: ['ACT', 'CBT', 'Mindfulness'],
    delivery: ['remote', 'in-person'],
    values: ['secular', 'lgbtq-affirming', 'culturally-responsive'],
    insurance: ['Premera', 'Regence', 'Out-of-network'],
    sessionRate: 185,
    slidingScale: false,
    acceptingClients: true,
    nextAvailable: 'Next week',
    availability: [
      { day: 'Mon', times: ['9:30 AM', '4:00 PM'] },
      { day: 'Tue', times: ['1:00 PM'] },
      { day: 'Thu', times: ['9:00 AM', '5:00 PM'] },
    ],
    languages: ['English', 'Korean'],
    rating: 4.8,
    reviewCount: 45,
  },
  {
    id: 'noah-feldman',
    name: 'Noah Feldman',
    pronouns: 'they/them',
    gender: 'nonbinary',
    credentials: [{ abbrev: 'LMFT', label: 'Licensed Marriage & Family Therapist' }],
    licenseNumber: 'LMFT-71208',
    licenseState: 'OR',
    verified: true,
    yearsExperience: 5,
    headline: 'LGBTQ+ identity, coming out, and chosen family.',
    bio: "Affirming therapy that doesn't make you the teacher. I work with queer and trans clients on identity, coming out, transition, relationships, and the everyday weight of navigating an unaccepting world. Gender-affirming, sex-positive, and grounded in real clinical care.",
    city: 'Portland',
    state: 'OR',
    concerns: ['identity', 'anxiety', 'relationships', 'depression'],
    modalities: ['IFS', 'Person-Centered', 'ACT'],
    delivery: ['remote', 'in-person'],
    values: ['lgbtq-affirming', 'secular', 'culturally-responsive'],
    insurance: ['Moda', 'PacificSource', 'Out-of-network'],
    sessionRate: 145,
    slidingScale: true,
    acceptingClients: true,
    nextAvailable: 'This week',
    availability: [
      { day: 'Tue', times: ['11:00 AM', '6:00 PM'] },
      { day: 'Fri', times: ['10:00 AM', '2:00 PM'] },
    ],
    languages: ['English'],
    rating: 4.9,
    reviewCount: 33,
  },
  {
    id: 'helen-park',
    name: 'Dr. Helen Park',
    pronouns: 'she/her',
    gender: 'female',
    credentials: [{ abbrev: 'MD', label: 'Psychiatrist' }],
    licenseNumber: 'MD-118744',
    licenseState: 'NY',
    verified: true,
    yearsExperience: 16,
    headline: 'Grief, loss, and late-life transitions.',
    bio: "Grief doesn't follow a schedule, and it doesn't end on the timeline other people expect. I sit with people through loss — of a person, a marriage, a body that used to work differently, a future they'd planned. The work is gentle and unhurried. As a psychiatrist I can coordinate medication where it helps, but most of our time is simply human.",
    city: 'New York',
    state: 'NY',
    concerns: ['grief', 'depression', 'anxiety', 'family'],
    modalities: ['Psychodynamic', 'Person-Centered', 'Mindfulness'],
    delivery: ['in-person', 'remote'],
    values: ['secular', 'culturally-responsive'],
    insurance: ['Aetna', 'Empire', 'Out-of-network'],
    sessionRate: 300,
    slidingScale: false,
    acceptingClients: true,
    nextAvailable: 'Next week',
    availability: [
      { day: 'Wed', times: ['2:00 PM'] },
      { day: 'Fri', times: ['11:00 AM', '3:00 PM'] },
    ],
    languages: ['English', 'Korean'],
    rating: 4.9,
    reviewCount: 61,
  },
];

// Each seed provider has a generated illustrated placeholder avatar in
// public/therapists/<id>.svg (offline DiceBear — see scripts/gen-avatars.mjs).
// Attaching the path here keeps the records tidy and guarantees it matches the
// id. Swap in real headshots by setting `photoUrl` on a record directly, or by
// dropping a file at the same path. If an image is missing, <Avatar> falls back
// to an initials monogram.
export const therapists: Therapist[] = directory.map((t) => ({
  ...t,
  photoUrl: t.photoUrl ?? `/therapists/${t.id}.svg`,
}));

export function getTherapist(id: string): Therapist | undefined {
  return therapists.find((t) => t.id === id);
}
